### PR TITLE
Pricefeed fixes

### LINKED ISSUE #303: pricefeed query markets formatting is bad
`kvcli q pricefeed assets`

```
- "Asset:\n\tMarket ID: btc:usd\n\tBase Asset: btc\n\tQuote Asset: usd\n\tOracles:
  Oracles:\n\tActive: true"
- "Asset:\n\tMarket ID: xrp:usd\n\tBase Asset: xrp\n\tQuote Asset: usd\n\tOracles:
  Oracles:\n\tActive: true"
- "Asset:\n\tMarket ID: kava:usd\n\tBase Asset: kava\n\tQuote Asset: usd\n\tOracles:
  Oracles:\n\tActive: true"
- "Asset:\n\tMarket ID: bnb:usd\n\tBase Asset: bnb\n\tQuote Asset: usd\n\tOracles:
  Oracles:\n\tActive: true"
```

- [ ] fix formatting
- [ ] rename assets to markets

### PR DESCRIPTION
**Pull request by karzak**
Fixed:
* params
* queries
* store methods

Closes: #303 #294

### CODE REVIEW

File: x/pricefeed/genesis.go [hunk 1]
```diff
@@ -5,23 +5,23 @@ import (
 )
 
 // InitGenesis sets distribution information for genesis.
-func InitGenesis(ctx sdk.Context, keeper Keeper, data GenesisState) {
-
-	// Set the assets and oracles from params
-	keeper.SetParams(ctx, data.Params)
+func InitGenesis(ctx sdk.Context, keeper Keeper, gs GenesisState) {
```
Comment (rhuairahrighairidh) [inline x/pricefeed/genesis.go]: nit: `InitGenesis` could call `data.Validate` to match other modules

Comment (karzak) [reply x/pricefeed/genesis.go]: 0069718
